apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: knowledge-share-app
    context: .
    docker: {}
  tagPolicy:
    gitCommit: {}
  local: {}
profiles:
  - name: build
    build:
      artifacts:
        - image: "{{ .DOCKER_REGISTRY }}/liatrio/knowledge-share-app"
          context: .
          docker: {}
      tagPolicy:
        gitCommit: {}
      local:
        push: true
