apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: knowledge-share-app
    context: .
    docker: {}
  tagPolicy:
    gitCommit: {}
  local: {}
deploy:
  helm:
    releases:
    - name: knowledge-share-app
      chartPath: charts/knowledge-share-app
      setValueTemplates:
        image.repository: "knowledge-share-app"
        image.tag: "latest"
profiles:
  - name: build
    build:
      artifacts:
        - image: knowledge-share-app
          context: .
          docker: {}
      tagPolicy:
        envTemplate:
            template: "{{ .DOCKER_REGISTRY }}/artifactory/{{ .IMAGE_NAME }}:{{ .GIT_COMMIT }}"
      local:
        push: true
    deploy: {}

