apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: knowledge-share-app
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: knowledge-share-app
      chartPath: charts/knowledge-share-app
      values:
        image: knowledge-share-app
profiles:
  - name: jenkins
    build:
      artifacts:
        - image: knowledge-share-app
      tagPolicy:
        gitCommit: {}
      local:
        push: true
    deploy: {}

