apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: knowledge-share-app
    context: .
    docker: {}
  tagPolicy:
    gitCommit: {}
  local: {}
profiles:
  - name: jenkins
    build:
      artifacts:
        - image: knowledge-share-app
          context: .
          docker: {}
      tagPolicy:
        envTemplate:
          template: "{{ .DOCKER_REGISTRY }}/liatrio/{{ .IMAGE_NAME }}:{{ .GIT_COMMIT }}"
      local:
        push: true
