apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: knowledge-share-app
    context: .
    docker: {}
  tagPolicy:
    gitCommit: {}
  local: {}
profiles:
  - name: jenkins
    build:
      artifacts:
        - image: knowledge-share-app
          context: .
          docker: {}
      tagPolicy:
        gitCommit: {}
      local: {}
    deploy:
      helm:
        releases:
        - name: knowledge-share-app
          chartPath: charts/knowledge-share-app
          setValueTemplates:
            image.repository: "knowledge-share-app"
            image.tag: "ad0cee476747f5d49e1827ecbb2c7f3d4ef53a78245a3e0216a141cd6f10f4b6"
