replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: knowledge-share-app
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 5
readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 5
service:
  type: NodePort
  name: knowledge-share-app
  servicePort: 8080
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - knowledge-share-app.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
