apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}-selector"
        version: "current"
    spec:
      containers:
      - name: "{{  .Chart.Name  }}"
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.service.servicePort }}
          httpHeaders:
          - name: Content-Type
            value: application/json
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.service.servicePort }}
          httpHeaders:
          - name: Content-Type
            value: application/json
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds}}
        ports:
        - containerPort: {{ .Values.service.servicePort}}
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
        env:
          - name: PORT
            value : "{{ .Values.service.servicePort }}"
